# default configuration
baseURL: http://etaipe-blog.s3-website-us-east-1.amazonaws.com/
languageCode: en-us
summaryLength: '10'
theme: kross-hugo
title: Kross

# default parameters
params:

# css plugins
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css

# js plugin
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  home: Home
  logo: ''

# theme color
  theme_color: '#41228e'

# contact info
  phone: +880 2544 658 256
  email: steve.fruits@email.com
  address: '125/A, CA Commercial Area, California, USA'

# meta description
  author: Johnathan Smith
  description: This is meta description

# google analytics
  google_analytics_id: ''

# baidu site verification
  baidu_site_verification: ''

# baidu analytics
  baidu_analytics_id: ''

# copyright
  copyright: 'Copyright &copy; 2021 a Theme by [Gethugothemes](https://gethugothemes.com)'

# preloader
  preloader:
    enable: true
    preloader: images/preloader.gif

# contact
    contact:
    enable: true
    form_action: '#'

# google map
  map:
    enable: true
    gmap_api: >-
      https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png

# cookies
    cookies:
    enable: true
    expire_days: 2

# social site
  social:
    - icon: ti-facebook
      URL: '#'
    - icon: ti-instagram
      URL: '#'
    - icon: ti-dribbble
      URL: '#'
    - icon: ti-twitter-alt
      URL: '#'

# menu
menu:
  main:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Blog
      weight: 2
    - URL: portfolio
      name: Portfolio
      weight: 3
    - URL: contact
      name: Contact
      weight: 4
