version: 2.1

orbs:
  hugo: circleci/hugo@1.2.2
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: my-site
      - aws-cli/setup:
          profile-name: circleci
      - run:
          name: Push files
          command: |
            BUCKET=$(aws ssm get-parameter --name "/app/portfolio-app/bucket" | jq ".Parameter.Value" | tr -d '"')
            aws s3 cp my-site/public s3://$BUCKET/ --recursive --acl public-read

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.88'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build
